---
title: "Data Driven Fantasy Football"
author: "Martin Sloley"
output:
    bookdown::html_document2:
        toc: true
        theme: united
---
# Links
- [Github repo](https://github.com/martin-nd/ff_2024)

# Introduction

This is a live report / readme of a data driven fantasy football project by myself and a friend of mine. Each post here will detail some of the work that we've done in the past week on this project, or some relevant update (draft / trades / model breakthroughs / etc). If you're following this feel free to check back every few weeks and see what progress we've made, or check back a day or two after a game and see what the results mean analytically.

On a personal note, this is my first attempt at doing sports analytics, and my sport growing up was swimming, so I'm extremely unfamiliar with both sports data and football in particular, but I'm hoping that what I lack in game knowledge, I make up for in mathematics, coding, and data science expertise. I guess we'll see.

# Draft Preparation / Pre-Draft Analytics (8-22-24)

In preparation for the draft, we have decided to focus on ranking players for each position based off of the points they could earn us in fantasy. To do this we've come up with our own fantasy version of EPA (expected points added)